/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cms;

/**
 *
 * @author Dell
 */
public class home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(home.class.getName());

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        about = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        cpassword = new javax.swing.JButton();
        schedule = new javax.swing.JButton();
        addclass = new javax.swing.JButton();
        announcement = new javax.swing.JButton();
        login = new javax.swing.JButton();
        fvoucher = new javax.swing.JButton();
        sassign = new javax.swing.JButton();
        announcement1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GLOBAL VISION");

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 153));
        jLabel7.setText("UNIVERSITY");

        about.setBackground(new java.awt.Color(204, 204, 204));
        about.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        about.setText("ABOUT");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/logo1.jpg"))); // NOI18N

        home.setBackground(new java.awt.Color(204, 204, 204));
        home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        profile.setBackground(new java.awt.Color(204, 204, 204));
        profile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        profile.setText("A");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(about, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(about, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 130));

        cpassword.setBackground(new java.awt.Color(204, 204, 204));
        cpassword.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        cpassword.setText("Change Password");
        cpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(cpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 233, 59));

        schedule.setBackground(new java.awt.Color(204, 204, 204));
        schedule.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        schedule.setText("Class Schedule");
        schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleActionPerformed(evt);
            }
        });
        getContentPane().add(schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 230, 59));

        addclass.setBackground(new java.awt.Color(204, 204, 204));
        addclass.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        addclass.setText("ADD Classes");
        addclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addclassActionPerformed(evt);
            }
        });
        getContentPane().add(addclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 230, 59));

        announcement.setBackground(new java.awt.Color(204, 204, 204));
        announcement.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        announcement.setText("Announcement");
        announcement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                announcementActionPerformed(evt);
            }
        });
        getContentPane().add(announcement, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 230, 59));

        login.setBackground(new java.awt.Color(255, 0, 51));
        login.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGOUT");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, 129, 59));

        fvoucher.setBackground(new java.awt.Color(204, 204, 204));
        fvoucher.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        fvoucher.setText("Fee Voucher");
        fvoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fvoucherActionPerformed(evt);
            }
        });
        getContentPane().add(fvoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 233, 60));

        sassign.setBackground(new java.awt.Color(204, 204, 204));
        sassign.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        sassign.setText("Show Assignment");
        sassign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sassignActionPerformed(evt);
            }
        });
        getContentPane().add(sassign, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 230, 59));

        announcement1.setBackground(new java.awt.Color(204, 204, 204));
        announcement1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        announcement1.setText("huhuhuh");
        announcement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                announcement1ActionPerformed(evt);
            }
        });
        getContentPane().add(announcement1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 230, 59));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/darkcms.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 910, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void announcementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_announcementActionPerformed
        // TODO add your handling code here:
        announcement a=new announcement();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_announcementActionPerformed

    private void cpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpasswordActionPerformed
        // TODO add your handling code here:
        cpassword cp=new cpassword();
        cp.setVisible(true);
        dispose();
    }//GEN-LAST:event_cpasswordActionPerformed

    private void fvoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fvoucherActionPerformed
        // TODO add your handling code here:
        voucher v=new voucher();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_fvoucherActionPerformed

    private void scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleActionPerformed
        // TODO add your handling code here:
        schedule sc=new schedule();
        sc.setVisible(true);
        dispose();
    }//GEN-LAST:event_scheduleActionPerformed

    private void sassignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sassignActionPerformed
        // TODO add your handling code here:
        sassign sas=new sassign();
        sas.setVisible(true);
        dispose();
    }//GEN-LAST:event_sassignActionPerformed

    private void addclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addclassActionPerformed
        // TODO add your handling code here:
        addclass add=new addclass();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_addclassActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        login l=new login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_loginActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        // TODO add your handling code here:
        profile p=new profile();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_profileActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        about a=new about();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_aboutActionPerformed

    private void announcement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_announcement1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_announcement1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about;
    private javax.swing.JButton addclass;
    private javax.swing.JButton announcement;
    private javax.swing.JButton announcement1;
    private javax.swing.JButton cpassword;
    private javax.swing.JButton fvoucher;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JButton profile;
    private javax.swing.JButton sassign;
    private javax.swing.JButton schedule;
    // End of variables declaration//GEN-END:variables
}
